// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'dart:io';

import 'package:firebase_core/firebase_core.dart';

FirebaseOptions firebaseOptions = Platform.isAndroid
    ? const FirebaseOptions(
        apiKey: 'AIzaSyDIFfan5plUnuhiVGGQ36t6kbQs9ZnbX84',
        appId: '1:886270077397:android:1c3ba8c139bb47dfedb55c',
        messagingSenderId: '886270077397',
        projectId: 'fooddelivery-9f962',
        storageBucket: 'fooddelivery-9f962.appspot.com',
      )
    : const FirebaseOptions(
        apiKey: 'AIzaSyDE8-ESkD2z7YcN6sjmxGQWMxJmuZ9qzhE',
        appId: '1:886270077397:ios:2027d2801b91d21aedb55c',
        messagingSenderId: '886270077397',
        projectId: 'fooddelivery-9f962',
        storageBucket: 'fooddelivery-9f962.appspot.com',
        iosBundleId: 'com.example.foodDelivery',
      );
